import * as React from "react";
import { cn } from "../lib/utils";
import { cva, type VariantProps } from "class-variance-authority";
import { ChevronDown } from "lucide-react"; export type AccordionVariant = "b2b" | "b2c" | "admin";
export type AccordionDensity = "compact" | "normal" | "comfortable"; export interface AccordionItem { id: string; title: string; content: React.ReactNode; disabled?: boolean; icon?: React.ReactNode; badge?: number | string; description?: string;
} export interface AccordionProps extends VariantProps<typeof accordionVariants> { density?: AccordionDensity; items: AccordionItem[]; allowMultiple?: boolean; expandedIds?: string[]; onExpandedChange?: (expandedIds: string[]) => void; containerClassName?: string; children?: React.ReactNode;
} const accordionVariants = cva( "border rounded-lg overflow-hidden", { variants: { variant: { b2b: "border-near-black divide-y divide-near-black", b2c: "border-near-black divide-y divide-near-black", admin: "border-near-black divide-y divide-near-black", }, }, defaultVariants: { variant: "b2b", }, }
); const densityStyles = { compact: { container: "px-3 py-2", title: "text-xs font-semibold", content: "text-xs px-3 py-2", gap: "gap-2", }, normal: { container: "px-4 py-3", title: "text-sm font-semibold", content: "text-sm px-4 py-3", gap: "gap-3", }, comfortable: { container: "px-6 py-4", title: "text-base font-semibold", content: "text-base px-6 py-4", gap: "gap-4", },
}; export const Accordion = React.forwardRef<HTMLDivElement, AccordionProps>( ( { items = [], allowMultiple = false, expandedIds = [], onExpandedChange, variant = "b2b", density = "normal", containerClassName, children, }, ref ) => { const styles = densityStyles[density || "normal"]; const [internalExpanded, setInternalExpanded] = React.useState<string[]>( expandedIds ); const isControlled = expandedIds && expandedIds.length >= 0; const expanded = isControlled ? expandedIds : internalExpanded; const handleToggle = (itemId: string) => { let newExpanded: string[]; if (expanded.includes(itemId)) { newExpanded = expanded.filter((id) => id !== itemId); } else { newExpanded = allowMultiple ? [...expanded, itemId] : [itemId]; } if (!isControlled) { setInternalExpanded(newExpanded); } onExpandedChange?.(newExpanded); }; return ( <div ref={ref} className={cn( accordionVariants({ variant }), containerClassName )} > {items.map((item) => { const isExpanded = expanded.includes(item.id); const isDisabled = item.disabled; return ( <div key={item.id} className={cn( "transition-colors", isDisabled && "opacity-50 cursor-not-allowed bg-near-black" )} > <button onClick={() => !isDisabled && handleToggle(item.id)} disabled={isDisabled} className={cn( styles.container, "w-full flex items-center justify-between cursor-pointer transition-colors", !isDisabled && "hover:bg-near-black", isExpanded && (variant === "b2b" ? "bg-apple-blue" : variant === "b2c" ? "bg-apple-blue" : "bg-near-black") )} aria-expanded={isExpanded} role="tab" > <div className={cn("flex items-center", styles.gap)}> {item.icon && ( <span className="text-near-black flex-shrink-0"> {item.icon} </span> )} <div className="text-left"> <p className={cn( styles.title, "text-near-black font-bold", isDisabled && "opacity-70" )} > {item.title} </p> {item.description && ( <p className="text-xs text-near-black mt-0.5"> {item.description} </p> )} </div> </div> <div className="flex items-center gap-2 flex-shrink-0"> {item.badge !== undefined && ( <span className={cn( "px-2 py-1 rounded-full text-[10px] font-bold", variant === "b2b" ? "bg-apple-blue/10 text-apple-blue" : variant === "b2c" ? "bg-apple-blue/10 text-apple-blue" : "bg-near-black text-near-black" )} > {item.badge} </span> )} <ChevronDown className={cn( "transition-transform flex-shrink-0", density === "compact" && "h-4 w-4", density === "normal" && "h-5 w-5", density === "comfortable" && "h-6 w-6", isExpanded && "rotate-180" )} /> </div> </button> {/* Expanded content */} {isExpanded && ( <div className={cn( styles.content, "bg-white", variant === "b2b" && "border-t-2 border-apple-blue", variant === "b2c" && "border-t-2 border-apple-blue", variant === "admin" && "border-t-2 border-near-black" )} role="tabpanel" > {item.content} </div> )} </div> ); })} {children} </div> ); }
); Accordion.displayName = "Accordion";
