import * as React from "react";
import { cn } from "../lib/utils";
import { cva, type VariantProps } from "class-variance-authority";
import { ChevronRight } from "lucide-react"; export type PageHeaderVariant = "b2b" | "b2c" | "admin";
export type PageHeaderDensity = "compact" | "normal" | "comfortable"; export interface BreadcrumbItem { label: string; href?: string; active?: boolean; icon?: React.ReactNode;
} export interface PageHeaderAction { label: string; onClick: () => void; variant?: "primary" | "secondary" | "danger"; disabled?: boolean; icon?: React.ReactNode;
} export interface PageHeaderProps extends VariantProps<typeof headerVariants> { title: string; subtitle?: string; icon?: React.ReactNode; breadcrumbs?: BreadcrumbItem[]; actions?: PageHeaderAction[]; description?: React.ReactNode; backgroundImage?: string; containerClassName?: string; titleClassName?: string; children?: React.ReactNode; onBreadcrumbClick?: (item: BreadcrumbItem) => void;
} const headerVariants = cva( "relative overflow-hidden border-b transition-colors", { variants: { variant: { b2b: " border-apple-blue/20", b2c: " border-apple-blue/20", admin: " border-near-black", }, density: { compact: "py-3", normal: "py-6", comfortable: "py-8", }, }, defaultVariants: { variant: "b2b", density: "normal", }, }
); const densityStyles = { compact: { container: "px-4 max-w-7xl mx-auto", title: "text-xl font-bold", subtitle: "text-xs", breadcrumb: "text-xs", gap: "gap-2", }, normal: { container: "px-6 max-w-7xl mx-auto", title: "text-2xl font-bold", subtitle: "text-sm", breadcrumb: "text-sm", gap: "gap-3", }, comfortable: { container: "px-8 max-w-7xl mx-auto", title: "text-3xl font-bold", subtitle: "text-base", breadcrumb: "text-base", gap: "gap-4", },
}; export const PageHeader = React.forwardRef<HTMLDivElement, PageHeaderProps>( ( { title, subtitle, icon, breadcrumbs = [], actions = [], description, backgroundImage, variant = "b2b", density = "normal", containerClassName, titleClassName, children, onBreadcrumbClick, }, ref ) => { const styles = densityStyles[density || "normal"]; return ( <div ref={ref} className={cn(headerVariants({ variant, density }))} style={ backgroundImage ? { backgroundImage: `url(${backgroundImage})` } : {} } > {backgroundImage && ( <div className="absolute inset-0 bg-black/40 z-0" /> )} <div className={cn( styles.container, "relative z-10", containerClassName )} > {/* Breadcrumbs */} {breadcrumbs.length > 0 && ( <div className={cn( "flex items-center mb-4", styles.gap )} > {breadcrumbs.map((item, index) => ( <div key={`breadcrumb-${index}`} className="flex items-center gap-2"> {item.icon && ( <span className="text-near-black"> {item.icon} </span> )} {item.href ? ( <button onClick={() => onBreadcrumbClick?.(item)} className={cn( styles.breadcrumb, "font-medium text-near-black hover:text-near-black transition-colors cursor-pointer" )} > {item.label} </button> ) : ( <span className={cn( styles.breadcrumb, "font-medium", item.active ? "text-near-black" : "text-near-black" )} > {item.label} </span> )} {index < breadcrumbs.length - 1 && ( <ChevronRight className="h-4 w-4 text-near-black" /> )} </div> ))} </div> )} {/* Title and actions row */} <div className="flex items-start justify-between gap-4 mb-2"> <div className="flex items-center gap-3 flex-1"> {icon && ( <div className="text-near-black"> {icon} </div> )} <div className="flex-1"> <h1 className={cn( styles.title, "text-near-black leading-tight", titleClassName )} > {title} </h1> </div> </div> {/* Actions */} {actions.length > 0 && ( <div className="flex items-center gap-2"> {actions.map((action, index) => ( <button key={`action-${index}`} onClick={action.onClick} disabled={action.disabled} className={cn( "px-4 py-2 rounded-lg font-semibold transition-colors flex items-center gap-2 text-sm", action.variant === "primary" && "bg-apple-blue text-white hover:bg-apple-blue disabled:opacity-50", action.variant === "secondary" && "bg-near-black text-near-black hover:bg-near-black disabled:opacity-50", action.variant === "danger" && "bg-near-black text-white hover:bg-near-black disabled:opacity-50", !action.variant && "bg-near-black text-near-black hover:bg-near-black disabled:opacity-50", action.disabled && "cursor-not-allowed" )} > {action.icon} {action.label} </button> ))} </div> )} </div> {/* Subtitle */} {subtitle && ( <p className={cn( styles.subtitle, "text-near-black font-medium mb-3" )} > {subtitle} </p> )} {/* Description */} {description && ( <div className="text-sm text-near-black mb-4"> {description} </div> )} {/* Children */} {children} </div> </div> ); }
); PageHeader.displayName = "PageHeader";
