import * as React from "react";
import { cn } from "../lib/utils";
import { cva, type VariantProps } from "class-variance-authority"; export type ToggleSwitcherVariant = "b2b" | "b2c" | "admin";
export type ToggleSwitcherDensity = "compact" | "normal" | "comfortable"; export interface ToggleSwitcherProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "type" | "onToggle">, VariantProps<typeof switcherVariants> { label?: string; description?: string; error?: string; successMessage?: string; touched?: boolean; containerClassName?: string; labelClassName?: string; errorClassName?: string; successClassName?: string; helperText?: string; required?: boolean; onToggle?: (checked: boolean) => void;
} const switcherVariants = cva( "relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50", { variants: { variant: { b2b: "bg-near-black focus-visible:ring-apple-blue focus-visible:ring-offset-white checked:bg-apple-blue", b2c: "bg-near-black focus-visible:ring-apple-blue focus-visible:ring-offset-white checked:bg-apple-blue", admin: "bg-near-black focus-visible:ring-apple-blue focus-visible:ring-offset-white checked:bg-near-black", }, density: { compact: "h-5 w-9", normal: "h-6 w-11", comfortable: "h-7 w-12", }, }, defaultVariants: { variant: "b2b", density: "normal", }, }
); const sliderVariants = cva( "pointer-events-none inline-block transform rounded-full bg-white shadow-apple ring-0 transition-transform", { variants: { density: { compact: "h-4 w-4", normal: "h-5 w-5", comfortable: "h-6 w-6", }, }, defaultVariants: { density: "normal", }, }
); const densityStyles = { compact: { label: "text-xs font-medium", container: "gap-1" }, normal: { label: "text-sm font-medium", container: "gap-2" }, comfortable: { label: "text-base font-medium", container: "gap-3" },
}; export const ToggleSwitcher = React.forwardRef< HTMLInputElement, ToggleSwitcherProps
>( ( { label, description, error, successMessage, touched = false, variant = "b2b", density = "normal", containerClassName, labelClassName, errorClassName, successClassName, helperText, required = false, disabled = false, className, checked, onToggle, onChange, ...props }, ref ) => { const styles = densityStyles[density || "normal"]; const [isChecked, setIsChecked] = React.useState(checked || false); const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => { const newChecked = e.target.checked; setIsChecked(newChecked); onToggle?.(newChecked); onChange?.(e); }; React.useEffect(() => { if (checked !== undefined) { setIsChecked(checked); } }, [checked]); return ( <div className={cn( "flex flex-col", styles.container, containerClassName )} > <div className="flex items-center gap-2"> <label className="relative inline-flex items-center cursor-pointer" htmlFor={props.id} > <input ref={ref} type="checkbox" disabled={disabled} checked={isChecked} onChange={handleChange} className="sr-only" {...props} /> <div className={cn( switcherVariants({ variant, density }), error && touched && "ring-2 ring-near-black ring-offset-2", successMessage && touched && "ring-2 ring-apple-blue ring-offset-2", className )} > <span className={cn( sliderVariants({ density }), "absolute top-1/2 left-1", isChecked && (density === "compact" ? "translate-x-4 -translate-y-1/2" : density === "comfortable" ? "translate-x-5 -translate-y-1/2" : "translate-x-5 -translate-y-1/2") )} /> </div> </label> {label && ( <label htmlFor={props.id} className={cn( styles.label, "text-near-black font-semibold cursor-pointer", required && "after:content-['*'] after:ml-1 after:text-near-black", disabled && "opacity-50 cursor-not-allowed", labelClassName )} > {label} </label> )} </div> {description && ( <p className={cn("text-xs text-near-black", density === "compact" && "hidden")}> {description} </p> )} {helperText && !error && !successMessage && ( <p className={cn("text-xs text-near-black")}> {helperText} </p> )} {error && touched && ( <p className={cn( "text-xs font-medium text-near-black", errorClassName )} > {error} </p> )} {successMessage && touched && ( <p className={cn( "text-xs font-medium text-apple-blue", successClassName )} > {successMessage} </p> )} </div> ); }
); ToggleSwitcher.displayName = "ToggleSwitcher";
