// Shared HTML document generation helpers for booking routes
import { DOCUMENT_COLORS } from "./commonTypes";

const C = DOCUMENT_COLORS; // short alias for template readability

export function generateHotelItineraryHtml(booking: any, customer: any): string {
  const checkIn = new Date(booking.checkInDate);
  const checkOut = new Date(booking.checkOutDate);
  const nights = Math.ceil((checkOut.getTime() - checkIn.getTime()) / (1000 * 60 * 60 * 24));
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Hotel Booking Itinerary - ${booking.bookingReference}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: ${C.textPrimary}; }
    .header { background: ${C.brandPrimary}; color: white; padding: 20px; border-radius: 8px; }
    .booking-ref { font-size: 24px; font-weight: bold; }
    .section { margin: 20px 0; padding: 15px; border: 1px solid ${C.border}; border-radius: 8px; }
    .hotel-info { background: ${C.surfaceMuted}; padding: 15px; border-radius: 8px; }
    .guest { background: ${C.surfaceMuted}; padding: 10px; margin: 5px 0; border-radius: 4px; }
    .detail-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid ${C.borderSoft}; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🏨 Hotel Booking Itinerary</h1>
    <div class="booking-ref">Booking Reference: ${booking.bookingReference}</div>
  </div>

  <div class="section hotel-info">
    <h2>${booking.hotelName}</h2>
    <div class="detail-row"><span>Room Type:</span><strong>${booking.roomType}</strong></div>
    <div class="detail-row"><span>Check-in:</span><strong>${booking.checkInDate}</strong></div>
    <div class="detail-row"><span>Check-out:</span><strong>${booking.checkOutDate}</strong></div>
    <div class="detail-row"><span>Number of Nights:</span><strong>${nights}</strong></div>
  </div>

  <div class="section">
    <h2>Guest Details</h2>
    ${booking.guests?.map((g: any) => `
      <div class="guest">
        <strong>${g.given_name} ${g.family_name}</strong><br>
        Email: ${g.email}<br>
        Phone: ${g.phone_number}
      </div>
    `).join('') || ''}
  </div>

  <div class="section">
    <h2>Contact Information</h2>
    <p><strong>Email:</strong> ${customer.email}</p>
    <p><strong>Phone:</strong> ${customer.phone}</p>
  </div>

  <div style="margin-top: 30px; text-align: center; color: ${C.textMuted};">
    <p>Generated by TripAlfa | ${new Date().toISOString()}</p>
  </div>
</body>
</html>`;
}

export function generateHotelInvoiceHtml(booking: any, customer: any, payment: any): string {
  const totalAmount = payment.total || booking.totalAmount || 0;
  const taxes = totalAmount * 0.1;
  const baseFare = totalAmount - taxes;
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Hotel Invoice - ${booking.bookingReference}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: ${C.textPrimary}; }
    .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid ${C.brandPrimary}; padding-bottom: 20px; }
    .invoice-title { font-size: 32px; color: ${C.brandPrimary}; }
    .invoice-number { font-size: 18px; color: ${C.textMuted}; }
    .section { margin: 20px 0; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid ${C.border}; }
    th { background: ${C.surfaceMuted}; }
    .total-row { font-weight: bold; font-size: 18px; background: ${C.brandPrimary}; color: white; }
    .footer { margin-top: 40px; text-align: center; color: ${C.textMuted}; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="invoice-title">HOTEL INVOICE</div>
      <div class="invoice-number">Invoice #INV-${Date.now()}</div>
    </div>
    <div>
      <strong>TripAlfa Travel</strong><br>Dubai, UAE<br>info@tripalfa.com
    </div>
  </div>

  <div class="section">
    <h3>Hotel: ${booking.hotelName}</h3>
    <p><strong>Room:</strong> ${booking.roomType}</p>
    <p><strong>Check-in:</strong> ${booking.checkInDate} | <strong>Check-out:</strong> ${booking.checkOutDate}</p>
  </div>

  <div class="section">
    <h3>Bill To:</h3>
    <p><strong>${customer.name}</strong><br>${customer.email}<br>${customer.phone}</p>
  </div>

  <div class="section">
    <h3>Booking Reference: ${booking.bookingReference}</h3>
    <table>
      <thead><tr><th>Description</th><th>Amount</th></tr></thead>
      <tbody>
        <tr><td>Room Charges (${booking.roomType})</td><td>${payment.currency || 'USD'} ${baseFare.toFixed(2)}</td></tr>
        <tr><td>Taxes & Fees (10%)</td><td>${payment.currency || 'USD'} ${taxes.toFixed(2)}</td></tr>
        <tr class="total-row"><td>Total</td><td>${payment.currency || 'USD'} ${totalAmount.toFixed(2)}</td></tr>
      </tbody>
    </table>
  </div>

  <div class="footer">
    <p>Payment Due: ${new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toLocaleDateString()}</p>
    <p>Generated by TripAlfa | ${new Date().toISOString()}</p>
  </div>
</body>
</html>`;
}

export function generateHotelReceiptHtml(booking: any, customer: any, payment: any): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Hotel Payment Receipt - ${booking.bookingReference}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: ${C.textPrimary}; }
    .header { background: ${C.success}; color: white; padding: 20px; border-radius: 8px; text-align: center; }
    .amount { font-size: 36px; font-weight: bold; }
    .section { margin: 20px 0; padding: 15px; border: 1px solid ${C.border}; border-radius: 8px; }
    .detail-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid ${C.borderSoft}; }
    .detail-row:last-child { border-bottom: none; }
  </style>
</head>
<body>
  <div class="header">
    <h1>✅ Payment Received</h1>
    <div class="amount">${payment.currency || 'USD'} ${(payment.total || 0).toFixed(2)}</div>
  </div>

  <div class="section">
    <h3>Receipt Details</h3>
    <div class="detail-row"><span>Receipt Number:</span><strong>RCP-${Date.now()}</strong></div>
    <div class="detail-row"><span>Booking Reference:</span><strong>${booking.bookingReference}</strong></div>
    <div class="detail-row"><span>Hotel:</span><strong>${booking.hotelName}</strong></div>
    <div class="detail-row"><span>Payment Method:</span><strong>${payment.paymentMethod || 'Card'}</strong></div>
    <div class="detail-row"><span>Payment Date:</span><strong>${new Date().toLocaleString()}</strong></div>
  </div>

  <div class="section">
    <h3>Guest Information</h3>
    <p><strong>${customer.name}</strong><br>${customer.email}</p>
  </div>

  <div style="margin-top: 30px; text-align: center; color: ${C.textMuted};">
    <p>Thank you for your payment! | Generated by TripAlfa</p>
  </div>
</body>
</html>`;
}

export function generateHotelVoucherHtml(booking: any, customer: any, voucherInfo: any): string {
  const checkIn = new Date(booking.checkInDate);
  const checkOut = new Date(booking.checkOutDate);
  const nights = Math.ceil((checkOut.getTime() - checkIn.getTime()) / (1000 * 60 * 60 * 24));
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Hotel Voucher - ${booking.bookingReference}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: ${C.textPrimary}; }
    .header { background: ${C.brandPrimary}; color: white; padding: 20px; border-radius: 8px; text-align: center; }
    .voucher-number { font-size: 24px; font-weight: bold; }
    .section { margin: 20px 0; padding: 15px; border: 1px solid ${C.border}; border-radius: 8px; }
    .hotel-info { background: ${C.surfaceMuted}; padding: 15px; border-radius: 8px; text-align: center; }
    .guest-info { background: ${C.surfaceMuted}; padding: 15px; border-radius: 8px; }
    .detail-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid ${C.borderSoft}; }
    .qr-placeholder { width: 120px; height: 120px; background: ${C.borderSoft}; margin: 20px auto; display: flex; align-items: center; justify-content: center; border-radius: 8px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🏨 Hotel Confirmation Voucher</h1>
    <div class="voucher-number">Voucher #: ${voucherInfo.voucherNumber}</div>
  </div>

  <div class="hotel-info">
    <h2>${booking.hotelName}</h2>
    <p><strong>Confirmation Number:</strong> ${booking.bookingReference}</p>
  </div>

  <div class="section">
    <h3>Stay Details</h3>
    <div class="detail-row"><span>Check-in:</span><strong>${booking.checkInDate} (After 2:00 PM)</strong></div>
    <div class="detail-row"><span>Check-out:</span><strong>${booking.checkOutDate} (Before 12:00 PM)</strong></div>
    <div class="detail-row"><span>Room Type:</span><strong>${booking.roomType}</strong></div>
    <div class="detail-row"><span>Number of Nights:</span><strong>${nights}</strong></div>
    <div class="detail-row"><span>Guests:</span><strong>${booking.guests?.length || 1}</strong></div>
  </div>

  <div class="section guest-info">
    <h3>Guest Information</h3>
    <p><strong>Primary Guest:</strong> ${customer.name}</p>
    <p><strong>Email:</strong> ${customer.email}</p>
    <p><strong>Phone:</strong> ${customer.phone}</p>
  </div>

  <div class="section">
    <h3>Important Information</h3>
    <ul>
      <li>Please present this voucher along with a valid photo ID at check-in</li>
      <li>Early check-in and late check-out are subject to availability</li>
      <li>Review cancellation policy at time of booking</li>
      <li>Contact hotel directly for special requests (extra bed, airport transfer, etc.)</li>
    </ul>
  </div>

  <div class="qr-placeholder">QR Code</div>

  <div style="margin-top: 30px; text-align: center; color: ${C.textMuted};">
    <p>Generated by TripAlfa | ${new Date().toISOString()}</p>
  </div>
</body>
</html>`;
}

export function generateHotelRefundNoteHtml(booking: any, customer: any, refund: any): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Hotel Refund Note - ${booking.bookingReference}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: ${C.textPrimary}; }
    .header { background: ${C.danger}; color: white; padding: 20px; border-radius: 8px; text-align: center; }
    .refund-amount { font-size: 36px; font-weight: bold; }
    .section { margin: 20px 0; padding: 15px; border: 1px solid ${C.border}; border-radius: 8px; }
    .detail-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid ${C.borderSoft}; }
  </style>
</head>
<body>
  <div class="header">
    <h1>💰 Hotel Booking Refund</h1>
    <div class="refund-amount">${refund.currency} ${refund.amount.toFixed(2)}</div>
  </div>

  <div class="section">
    <h3>Refund Details</h3>
    <div class="detail-row"><span>Refund Number:</span><strong>${refund.refundNumber}</strong></div>
    <div class="detail-row"><span>Original Booking:</span><strong>${booking.bookingReference}</strong></div>
    <div class="detail-row"><span>Hotel:</span><strong>${booking.hotelName}</strong></div>
    <div class="detail-row"><span>Reason:</span><strong>${refund.reason}</strong></div>
    <div class="detail-row"><span>Processed Date:</span><strong>${new Date().toLocaleString()}</strong></div>
    <div class="detail-row"><span>Status:</span><strong style="color: ${C.success};">COMPLETED</strong></div>
  </div>

  <div class="section">
    <h3>Refund To</h3>
    <p><strong>${customer.name}</strong><br>${customer.email}</p>
  </div>

  <div style="margin-top: 30px; text-align: center; color: ${C.textMuted};">
    <p>Generated by TripAlfa | ${new Date().toISOString()}</p>
  </div>
</body>
</html>`;
}

// ============================================================================
// Flight document generators - thin wrappers using the shared DOCUMENT_COLORS
// ============================================================================

export function generateItineraryHtml(booking: any, customer: any): string {
  const passengers = booking.passengers || [];
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Flight Itinerary - ${booking.bookingReference}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: ${C.textPrimary}; }
    .header { background: ${C.brandPrimary}; color: white; padding: 20px; border-radius: 8px; }
    .booking-ref { font-size: 24px; font-weight: bold; }
    .section { margin: 20px 0; padding: 15px; border: 1px solid ${C.border}; border-radius: 8px; }
    .passenger { background: ${C.surfaceMuted}; padding: 10px; margin: 5px 0; border-radius: 4px; }
    .detail-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid ${C.borderSoft}; }
  </style>
</head>
<body>
  <div class="header">
    <h1>✈️ Flight Itinerary</h1>
    <div class="booking-ref">Booking Reference: ${booking.bookingReference}</div>
  </div>

  <div class="section">
    <h2>Passenger Details</h2>
    ${passengers.map((p: any) => `
      <div class="passenger">
        <strong>${p.given_name} ${p.family_name}</strong><br>
        Email: ${p.email || 'N/A'}
      </div>
    `).join('')}
  </div>

  <div class="section">
    <h2>Contact Information</h2>
    <p><strong>Email:</strong> ${customer.email}</p>
    <p><strong>Phone:</strong> ${customer.phone}</p>
  </div>

  <div style="margin-top: 30px; text-align: center; color: ${C.textMuted};">
    <p>Generated by TripAlfa | ${new Date().toISOString()}</p>
  </div>
</body>
</html>`;
}

export function generateInvoiceHtml(booking: any, customer: any, payment: any): string {
  const totalAmount = payment.total || booking.totalAmount || 0;
  const taxes = totalAmount * 0.1;
  const baseFare = totalAmount - taxes;
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Flight Invoice - ${booking.bookingReference}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: ${C.textPrimary}; }
    .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid ${C.brandPrimary}; padding-bottom: 20px; }
    .invoice-title { font-size: 32px; color: ${C.brandPrimary}; }
    .invoice-number { font-size: 18px; color: ${C.textMuted}; }
    .section { margin: 20px 0; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid ${C.border}; }
    th { background: ${C.surfaceMuted}; }
    .total-row { font-weight: bold; font-size: 18px; background: ${C.brandPrimary}; color: white; }
    .footer { margin-top: 40px; text-align: center; color: ${C.textMuted}; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="invoice-title">FLIGHT INVOICE</div>
      <div class="invoice-number">Invoice #INV-${Date.now()}</div>
    </div>
    <div>
      <strong>TripAlfa Travel</strong><br>Dubai, UAE<br>info@tripalfa.com
    </div>
  </div>

  <div class="section">
    <h3>Booking Reference: ${booking.bookingReference}</h3>
    <table>
      <thead><tr><th>Description</th><th>Amount</th></tr></thead>
      <tbody>
        <tr><td>Base Fare</td><td>${payment.currency || 'USD'} ${baseFare.toFixed(2)}</td></tr>
        <tr><td>Taxes & Fees (10%)</td><td>${payment.currency || 'USD'} ${taxes.toFixed(2)}</td></tr>
        <tr class="total-row"><td>Total</td><td>${payment.currency || 'USD'} ${totalAmount.toFixed(2)}</td></tr>
      </tbody>
    </table>
  </div>

  <div class="section">
    <h3>Bill To:</h3>
    <p><strong>${customer.name}</strong><br>${customer.email}<br>${customer.phone}</p>
  </div>

  <div class="footer">
    <p>Payment Due: ${new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toLocaleDateString()}</p>
    <p>Generated by TripAlfa | ${new Date().toISOString()}</p>
  </div>
</body>
</html>`;
}

export function generateReceiptHtml(booking: any, customer: any, payment: any): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Flight Payment Receipt - ${booking.bookingReference}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: ${C.textPrimary}; }
    .header { background: ${C.success}; color: white; padding: 20px; border-radius: 8px; text-align: center; }
    .amount { font-size: 36px; font-weight: bold; }
    .section { margin: 20px 0; padding: 15px; border: 1px solid ${C.border}; border-radius: 8px; }
    .detail-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid ${C.borderSoft}; }
    .detail-row:last-child { border-bottom: none; }
  </style>
</head>
<body>
  <div class="header">
    <h1>✅ Payment Received</h1>
    <div class="amount">${payment.currency || 'USD'} ${(payment.total || 0).toFixed(2)}</div>
  </div>

  <div class="section">
    <h3>Receipt Details</h3>
    <div class="detail-row"><span>Receipt Number:</span><strong>RCP-${Date.now()}</strong></div>
    <div class="detail-row"><span>Booking Reference:</span><strong>${booking.bookingReference}</strong></div>
    <div class="detail-row"><span>Payment Method:</span><strong>${payment.paymentMethod || 'Card'}</strong></div>
    <div class="detail-row"><span>Payment Date:</span><strong>${new Date().toLocaleString()}</strong></div>
  </div>

  <div class="section">
    <h3>Passenger Information</h3>
    <p><strong>${customer.name}</strong><br>${customer.email}</p>
  </div>

  <div style="margin-top: 30px; text-align: center; color: ${C.textMuted};">
    <p>Thank you for your payment! | Generated by TripAlfa</p>
  </div>
</body>
</html>`;
}

export function generateETicketHtml(booking: any, customer: any, ticketInfo: any): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>E-Ticket - ${booking.bookingReference}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: ${C.textPrimary}; }
    .header { background: ${C.brandPrimary}; color: white; padding: 20px; border-radius: 8px; text-align: center; }
    .ticket-number { font-size: 24px; font-weight: bold; }
    .section { margin: 20px 0; padding: 15px; border: 1px solid ${C.border}; border-radius: 8px; }
    .detail-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid ${C.borderSoft}; }
    .qr-placeholder { width: 120px; height: 120px; background: ${C.borderSoft}; margin: 20px auto; display: flex; align-items: center; justify-content: center; border-radius: 8px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>✈️ E-Ticket</h1>
    <div class="ticket-number">Ticket #: ${ticketInfo.ticketNumber}</div>
  </div>

  <div class="section">
    <h3>Booking Details</h3>
    <div class="detail-row"><span>Booking Reference:</span><strong>${booking.bookingReference}</strong></div>
    <div class="detail-row"><span>Issued At:</span><strong>${new Date().toLocaleString()}</strong></div>
  </div>

  <div class="section">
    <h3>Passenger Information</h3>
    <p><strong>${customer.name}</strong><br>${customer.email}</p>
  </div>

  <div class="qr-placeholder">QR Code</div>

  <div style="margin-top: 30px; text-align: center; color: ${C.textMuted};">
    <p>Generated by TripAlfa | ${new Date().toISOString()}</p>
  </div>
</body>
</html>`;
}

export function generateRefundNoteHtml(booking: any, customer: any, refund: any): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Flight Refund Note - ${booking.bookingReference}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: ${C.textPrimary}; }
    .header { background: ${C.danger}; color: white; padding: 20px; border-radius: 8px; text-align: center; }
    .refund-amount { font-size: 36px; font-weight: bold; }
    .section { margin: 20px 0; padding: 15px; border: 1px solid ${C.border}; border-radius: 8px; }
    .detail-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid ${C.borderSoft}; }
  </style>
</head>
<body>
  <div class="header">
    <h1>💰 Flight Booking Refund</h1>
    <div class="refund-amount">${refund.currency} ${refund.amount.toFixed(2)}</div>
  </div>

  <div class="section">
    <h3>Refund Details</h3>
    <div class="detail-row"><span>Refund Number:</span><strong>${refund.refundNumber}</strong></div>
    <div class="detail-row"><span>Original Booking:</span><strong>${booking.bookingReference}</strong></div>
    <div class="detail-row"><span>Reason:</span><strong>${refund.reason}</strong></div>
    <div class="detail-row"><span>Processed Date:</span><strong>${new Date().toLocaleString()}</strong></div>
    <div class="detail-row"><span>Status:</span><strong style="color: ${C.success};">COMPLETED</strong></div>
  </div>

  <div class="section">
    <h3>Refund To</h3>
    <p><strong>${customer.name}</strong><br>${customer.email}</p>
  </div>

  <div style="margin-top: 30px; text-align: center; color: ${C.textMuted};">
    <p>Generated by TripAlfa | ${new Date().toISOString()}</p>
  </div>
</body>
</html>`;
}